version: "3.8"

services:
    pdf-generator-api:
        build: .
        ports:
            - "8000:8000"
        environment:
            - PYTHONPATH=/app
            - LOG_LEVEL=INFO
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        volumes:
            # Montar el código para hot reload (excluyendo archivos innecesarios)
            - ./app:/app/app
            - ./requirements.txt:/app/requirements.txt
            # Los templates y static están dentro de app/, así que se montan automáticamente
            # Excluir archivos que no necesitan hot reload
            - /app/venv
            - /app/__pycache__
            - /app/.pytest_cache
            - /app/.git
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8000/health",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
